// <auto-generated />
using Fruit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace duett_tech_challenge_api.Migrations
{
    [DbContext(typeof(FruitDbContext))]
    [Migration("20230316211157_InitDbMigration")]
    partial class InitDbMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fruit.Model.FruitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ValueOne")
                        .HasColumnType("integer");

                    b.Property<int>("ValueTwo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Fruit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Banana",
                            ValueOne = 10,
                            ValueTwo = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Maça",
                            ValueOne = 0,
                            ValueTwo = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
